### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [laabsky/DonationTracker#1]
You have a solid project idea. I hope that by being your own customer, this will be fun to build!

- [x] some broken links on the main page (readme.md)
- [x] Project plan - is this accurate for your project? For example, are you using the google maps api?  Are all entities, tables, and jsps accounted for?
- [x] Time log should include time for the class as well as the project. If you want to track time for non-project work elsewhere, that is ok, just let me know where that is.

**Comment by laabsky** [comment]
Done!
