### ISSUE TITLE
Instructor Feedback - Week 4 Exercise

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [laabsky/DonationTracker#2]
- [x] There is a ${filepath} directory created with your log files - instead log files should go into a valid path in your project. The cause is likely that ${file path} in your log4j2.properties file is not defined anywhere.
- [x] This method isn't necessary: https://github.com/laabsky/DonationTracker/blob/924747e2c64fe44c0cc2716aa17705cda0521739/src/main/java/DonationTracker/persistence/UserDao.java#L40. I had it in the demo for demonstration purposes only - instead use the getByProperty methods which are much more flexible.
- [x] Your user profile screen has city and state. Should this be in the user class and table as well?

**Comment by laabsky** [comment]
Decided that those inclusions for the user profile wasn't necessary. For v2, I'd like to include them with added functionality for the API to return local results.
