### ISSUE TITLE
Design/Code Review 1

### ISSUE THREAD

**Issue by jereladams** [laabsky/DonationTracker#4]
# Design/Code Review 1

### Reviewer: Jerel

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Good job explaining problem and solution.  Fix typo "aloow" in last sentence.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Consistence screen layouts and good work flow. Add ability to Edit donation from landing page. Finish adding links to your Application Flow and Database Design docs in the readMe.  |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Good job normalizing data and creating lookup table. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages. | N/A

**Comment by pawaitemadisoncollege** [comment]
@jereladams Did you check for system.out.println statements?

**Comment by laabsky** [comment]
Changes implemented!
