### ISSUE TITLE
Instructor Review - Week 14

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [laabsky/DonationTracker#7]
- [x] Reminder to address and close (once complete) any open issues
- [x] This class/method https://github.com/laabsky/DonationTracker/blob/2aab3fb2466b2fc9f1200993ff18d80fc3218729/src/main/java/DonationTracker/controller/SearchUser.java#L33 seems to be doing a lot of work - searching for users and consuming a web service. The web service consumption is probably better placed into its own class/methods for easier reuse. Consider adding a Dao type class for this work in your persistence package.
 - [ ] Be sure to include user-friendly error-handling. Consider what happens if the DB is down or the web service you consume is down.  
- [x] Web.xml likely needs updating with regard to restricted resources. Remember that both jsps and servlets should be restricted (not just the jsps as a savvy user/hacker will try to access the servlets too).
- [ ] Be sure to include a generic dao so eliminate the redundant code in the existing daos.
- [x] Remember to use log4j2 rather than printing out stack traces to the console: https://github.com/laabsky/DonationTracker/blob/2aab3fb2466b2fc9f1200993ff18d80fc3218729/src/test/java/DonationTracker/test/Database.java#L44
- [x] Remember to use properties files to externalize values such as web service urls.

**Comment by laabsky** [comment]
Implemented what I could. v2 would have more security and the generic dao.

**Comment by laabsky** [comment]
Tried to add security for servlets and it broke everything. Needed to revert back.

**Comment by pawaitemadisoncollege** [comment]
Start small! Secure one jsp and its related servlet first, get that working before moving on to any others. That way everything won't be broken ;)
